### ISSUE TITLE
Woocomerce Improvements (Single and Archive Product)

### ISSUE THREAD

**Issue by estraatios** [soflyy/oxygen-bugs-and-features#1094]
I started building a woo website and there are a lot of things missing.

Things I would like to see in for woocommerce

Products List (Archive Product)

1.  Be able to change the number of products to show on a page.
2.  Be able to add the category of the product.
3.  Be able to add a short description of the product.
4.  Be able to hide or show each element separately
5.  Be able to change the add to cart text button (and read more button for no prices)
6.  Be able to show the breadcrumbs on the top of the list. Also, be able to change the Home category.
7.  Be able to hide the toolbar on top
8.  Be able to add a button in the toolbar so the visitor can change the layout to rows instead of grid
9.  Be able to add a hover effect to images (zoom, swap)
10. Be able to change the background color of the product div

Product Builder (Single Product)

1.  Be able to add breadcrumbs
2.  Be able to change the number of related products and upsells along with the columns
3.  Be able to add variations of a product and change the layout (radio, check, select, etc)
4. Be able to add group product options and change the layout.

Thanks

**Comment by jamescrabb** [comment]
Some of these I with

**Comment by jasperf** [comment]
The product add to cart button now seems to load all attributes and variations. I would love to be able to add this where I want them. Now they are all added underneath each other. So this comments ads to your product builder no. 3-4 as an agreement I would say.

**Comment by vaztimur** [comment]
+1

**Comment by jasperf** [comment]
I would like to be able to add product builder variations, attributes and other product add-ons created by  [WooCommerce Product Add-On Ultimate](https://pluginrepublic.com/wordpress-plugins/woocommerce-product-add-ons-ultimate/) as separate elements. That would be very useful. Now they are all added under the _product cart button_ element in that can create a very long column inside a table.

**Comment by Hud1ai2** [comment]
Exactly. I would like to change the default design of the product list module. But after some time of work with product list I'm able to do
1. Add and show breadcrumbs (you can use it from Yoast, RankMath or Woocommerce itself.
2. Add and show the product atributes.
3. Add and change the size and text of the button.

But what is driving me nuts and what is really complicated to achieve
1. If you add the rating module to your custom product list, it will be displayed as a text and not as stars.
2. Adding price in some custom format is also hard to do.
3. I don't know if my solution will work with filtering etc.

**Comment by johndoe1318** [comment]
Simply being able to show / hide archive title and description from the product listing would be great already

**Comment by marks1974** [comment]
Just came across a problem listed on this post whilst making a WooCommerce site which seems strange it is not already available. In the product builder --> layout you have the option to choose from a 1-5 column layout making it nice and responsive. Yet if you add a related products item to a single product layout, you only have the option of 2, 3 or 4 columns. It needs to have the single column layout option as well on smaller screens. A 2 column layout looks really bad and squashes the content. I hope this can be added.
![Columns Issue](https://user-images.githubusercontent.com/13849426/94049033-4621d700-fdcc-11ea-905f-2d2b8aaaed31.png)

**Comment by KittenCodes** [comment]
@marks1974 

Here's some CSS that can be added to a stylesheet via Manage > Stylesheets in the top right of the builder to make the Related Products element responsive:

```css
@media only screen and (max-width: 992px){
  .woocommerce ul.products[class*=columns-] li.product, .woocommerce-page ul.products[class*=columns-] li.product{
      width: 33.3% !important;
  }
}

@media only screen and (max-width: 768px){
  .woocommerce ul.products[class*=columns-] li.product, .woocommerce-page ul.products[class*=columns-] li.product {
      width: 50% !important;
  }
}

@media only screen and (max-width: 480px){
  .woocommerce ul.products[class*=columns-] li.product, .woocommerce-page ul.products[class*=columns-] li.product {
      width: 100% !important;
  }
}
```
