### ISSUE TITLE
Default WordPress Image Alignment Fails

### ISSUE THREAD

**Issue by jammerinbc** [soflyy/oxygen-bugs-and-features#1151]
Default WordPress Image Alignment Fails. Oxygen 3.3

Pages created with default WordPress editor. Image Alignment ignored.
Align right Align left do not work and all padding is removed

**Comment by KittenCodes** [comment]
Please add the following CSS to a stylesheet via Manage > Stylesheets in the top right of the builder:

```css
.aligncenter {
    display: block;
    margin-left: auto;
    margin-right: auto;
}

.alignleft {
    float: left;
    margin: 0.5em 1em 0.5em 0;
}

.alignright {
    float: right;
    margin: 0.5em 0 0.5em 1em;
}

```
