### ISSUE TITLE
Gallery element can't set images per row for seperate breakpoints

### ISSUE THREAD

**Issue by samvandenbossche** [soflyy/oxygen-bugs-and-features#1226]
**Describe the bug**
When I toggle breakpoints to reduce the items per row for the gallery element it overrides the value on the other breakpoints

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
https://oxygen-qyvkktg8kvs9k.oxygen-demo.qsandbox.me/sample-page/

**To Reproduce**
- add a gallery element  with 3 items per row 
- on one of the smaller breakpoints set the items per row to 1 
- when you go back to the 'All devices' breakpoint that too is set to 1

**Expected behavior**
I should be able to change the items per row for smaller devices

**What actually happens**
items per row on all devices need to be the same

**Desktop (please complete the following information):**
- OS: windows 10
 - Browser chrome
 - Oxygen Version 3.3.1

**Comment by KittenCodes** [comment]
@samvandenbossche The number of images per row in the Gallery element isn't whitelisted for the different break points. However, you can change the images per row using CSS. Here's an example:

```css
@media only screen and (max-width: 980px){
  #_gallery-2-29.oxy-gallery-flex .oxy-gallery-item {
      width: calc(50% - 10px - 10px);
  }
}

```
