### ISSUE TITLE
Align Image under gutenberg dont work with Oxygen

### ISSUE THREAD

**Issue by zbyneksmetana** [soflyy/oxygen-bugs-and-features#1741]
**Describe the bug**
I create post in  Gutenberg editor (classical block with text and one align center "cat image" )
![image](https://user-images.githubusercontent.com/10263189/100218734-6af21200-2f15-11eb-9df6-61ba2ebcc8c3.png)

When i create Oxygen template for posts (place inner conntent into section ect) "cat image"  **is align to the left not center**
![image](https://user-images.githubusercontent.com/10263189/100220460-b1487080-2f17-11eb-9b39-bc95bb99b223.png)

**Is it posible to fix this problem? 
By the way, what is the recommendation when creating posts ... under Gutenberg editor or always in Oxygen editor ?** 

P.S. Sorry for language mistakes

 
**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes

**Comment by KittenCodes** [comment]
@zbyneksmetana 

Please add the following CSS to a stylesheet via Manage > Stylesheets in the top right of the builder:

```css
.aligncenter {
    display: block;
    margin-left: auto;
    margin-right: auto;
}

.alignleft {
    float: left;
    margin: 0.5em 1em 0.5em 0;
}

.alignright {
    float: right;
    margin: 0.5em 0 0.5em 1em;
}
```
