### ISSUE TITLE
Composite Dropdown Button Remains Open in Header Builder

### ISSUE THREAD

**Issue by kevingeary** [soflyy/oxygen-bugs-and-features#1976]
When I add the composite dropdown button to my primary template in the header builder, it's state is always open which makes it get in the way of editing and is overall just a poor user experience.

**Expected behavior**
The button should be closed in the builder unless clicking the container element to edit items.

**What actually happens**
The button is always in an active state and its child container is always open.

**Comment by KittenCodes** [comment]
@kevingeary 

To hide the dropdown child menu in the builder, please comment out the code on the CSS tab of the Dropdown Button Code Code Block.

I suggest commenting it out and not removing it as you'd need to re-enable the code to be able to make changes to the child items in the future.

Here's what you'd need to change the code to:

```css
/*body.ng-scope .oxel_dropdown_button__submenu--hidden {
 opacity: 1;
 pointer-events: initial;
}*/
```
