### ISSUE TITLE
Line-height not present in options in oxygen_vsb_get_global_styles

### ISSUE THREAD

**Issue by ciscoheat** [soflyy/oxygen-bugs-and-features#2003]
**Describe the bug**
File: `component-framework\component-init.php`
Method:  `oxygen_vsb_get_global_styles`

While debugging a strange cache issue (that occurred because `upload_dir` was set incorrectly in WP) I noticed that the `$options` object doesn't always contain a `line-height` key when customizing the global fonts, making it render illegal css for line-height.

A part of what it generates in `universal.css`:

```css
body {font-family: 'EB Garamond';}body {line-height: 1.45;font-size: 100%;font-weight: 400;color: #404040;}.oxy-nav-menu-hamburger-line {background-color: #404040;}h1, h2, h3, h4, h5, h6 {font-family: 'Lora';font-size: 2.815rem;font-weight: 500;line-height: 1.45;}h2, h3, h4, h5, h6{font-size: 2.289rem;line-height: ;}h3, h4, h5, h6{font-size: 1.861rem;line-height: ;}h4, h5, h6{font-size: 1.513rem;line-height: ;}h5, h6{font-size: 18px;line-height: ;}h6{font-size: 16px;line-height: ;}
```

Chrome handles it at least, but it would be nice to have this cleaned up.
