### ISSUE TITLE
issue with Product images - Layout

### ISSUE THREAD

**Issue by pgwthf** [soflyy/oxygen-bugs-and-features#2123]
Hi,

I'd like to report what I think may be a bug. If it is a feature I'd be disappointed :)

See:
https://oxygen-qyvksbkmahhfl.oxygen-demo.qsandbox.me/?ct_template=24&ct_builder=true

When I use the "product images" component, there are 4 options for "thumbnails layout", with 3 of them the image itself is shown as well but with the "Grid" option the main image is not present. 

AFAIK this is Woocommerce functionality that is being used in Oxygen, in Elementor (where I am transitioning from) it is working as I expected, i.e. main picture on top, grid below it, when you click on a grid image, it displays in the main area (see e.g. here: https://glaskasten.de/en/webshop/glaskasten-gk1-model-train-display-case-with-8-shelves-of-120cm/ )

If this is not a bug but a feature, is there another way to show multiple (e.g. 10) thumbnails with the main image area above it? The other option "Horizontally Bottom" also doesn't work, as only about 5 thumbnails can be shown, the others are invisible and scrolling does not really work....

Best regards,

Edwin
Oxygen username EvO

**Comment by KittenCodes** [comment]
@pgwthf Please set the layout to "Horizontally Bottom" and then add the following CSS to a stylesheet via Manage > Stylesheets in the top right of the builder to show the thumbnails as a Grid:

```css
.woocommerce div.product .oxy-product-images div.images .flex-control-thumbs li, .woocommerce div.product div.images .flex-control-thumbs li {
    width: 25%;
}

.woocommerce div.product .oxy-product-images div.images .flex-control-thumbs, .woocommerce div.product div.images .flex-control-thumbs {
    flex-wrap: wrap;
    overflow: auto;
}
```
