### ISSUE TITLE
Section Component: Image Overlay Color on Class

### ISSUE THREAD

**Issue by avviodigital** [soflyy/oxygen-bugs-and-features#2667]
Unable to use utility class to set Image Overlay Color in Section > Background.

**Comment by KittenCodes** [comment]
@avviodigital 

This isn't a bug.

If you set the background image via the same class as the overlay colour, it will work. If you set them using different classes, or if the image is set via the ID, then it won't work.

This is because the image and the overlay colour are part of the same CSS rule:

```css
.my-class {
    background-image: linear-gradient(rgba(0,0,0,0.34), rgba(0,0,0,0.34)), url(https://site.com/wp-content/uploads/2022/01/01.jpg);
}
```
