### ISSUE TITLE
(2.3) "Only Show In Sticky" Header Row Appears at 1120px Viewport Width

### ISSUE THREAD

**Issue by Spellhammer** [soflyy/oxygen-bugs-and-features#292]
Steps to replicate:

1. Create a Header Builder
2. Enable Sticky
3. Add a Header Row set to "Show in Sticky Only"
4. Preview viewport at 1120px

The Header Row that's set to "Show in Sticky Only" will appear at 1120px and below.

CSS to fix this:
```CSS
.oxy-sticky-header .oxygen-show-in-sticky-only {
    display:  none;
}

.oxy-sticky-header.oxy-sticky-header-active .oxygen-show-in-sticky-only {
    display: block;
}
```
