### ISSUE TITLE
Some checkboxes appear empty even when checked (problem identified)

### ISSUE THREAD

**Issue by guyinpv** [soflyy/oxygen-bugs-and-features#3198]
**Describe the bug**
Sometimes a checkbox in the admin panel does not show the "check" svg icon, so it appears unchecked at all times.
It doesn't happen with every checkbox. For example if you go to a div and go to Effects->Animate On Scroll and check the box, it looks normal. Most checkboxes are normal.
Now go to a Header Builder element under the Sticky settings and click "Enable Sticky Header" or "Fade In Sticky". These don't appear to be checked because the background image is set to none.

On the non-working one, there is a class `oxygen-option-default` that the working checkbox doesn't use. Because of this class, the `background-image: none;` style is taking precedence due to CSS specificity. Here is the CSS:

(From flex-ui.css)
```css
.oxygen-checkbox-checkbox-active:before {
  background-image: url('../oxygen-icons/other/checkbox.svg');
  background-repeat: no-repeat;
  background-position: center center;
}
.oxygen-checkbox-checkbox-active.oxygen-option-default:before {
  background-image: none;
}
```
Note how the 2nd class has `oxygen-option-default` and so it wins specificity over the active class:
`<div class="oxygen-checkbox-checkbox oxygen-option-default oxygen-checkbox-checkbox-active">`

![should be checked](https://user-images.githubusercontent.com/708955/212576371-b5c9d0a0-be20-4e4d-abcd-9daabad6c2b4.jpg)

![wrong class applied](https://user-images.githubusercontent.com/708955/212576376-fc28b391-8aab-4906-b3ec-7c87d89e43c1.jpg)
