### ISSUE TITLE
Product Upsells - Unable to set columns value on individual viewport sizes for 'Product Upsells'

### ISSUE THREAD

**Issue by websitesinkent** [soflyy/oxygen-bugs-and-features#920]
**Describe the bug**
I am unable to set the column arrangement for all the viewport size options on the product upsells oxygen element. I have tested this on your sandbox site and the same error occurs. It allows you to set the arrangement for 'All Devices' but not for other viewport sizes.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
https://oxygen-qwwj8nnbzgr8k.oxygen-demo.qsandbox.me/product/test-product-1/

**To Reproduce**
1. Go to 'Oxygen > Templates > Product'
2. Click on 'Product Upsells Element'
3. Switch between viewport sizes and try to click on the columns options.

Thanks.

**Comment by KittenCodes** [comment]
@websitesinkent The Product Upsells element hasn't been whitelisted for different breakpoints. However, you can change the column count on different breakpoints using CSS:

```css
@media only screen and (max-width: 992px){
  .woocommerce ul.products[class*=columns-] li.product, .woocommerce-page ul.products[class*=columns-] li.product{
      width: 33.3% !important;
  }
}

@media only screen and (max-width: 768px){
  .woocommerce ul.products[class*=columns-] li.product, .woocommerce-page ul.products[class*=columns-] li.product {
      width: 50% !important;
  }
}

@media only screen and (max-width: 480px){
  .woocommerce ul.products[class*=columns-] li.product, .woocommerce-page ul.products[class*=columns-] li.product {
      width: 100% !important;
  }
}
```
